"""Generator for ``shared/_config_constants.py``.

The flat YAML config files (everything except ``map.yaml``) are compiled into a real
``.py`` file with literal ``NAME = value`` assignments instead of being injected into
``globals()`` at runtime. A dynamically-injected name has no static definition an IDE can
see, so "Find All References" / "Go to Definition" can't trace it back to its source; a
literal assignment (with a comment naming its YAML file/key) can be navigated to directly.
"""
from __future__ import annotations

import sys
from pathlib import Path

import yaml

_CONFIG_DIR = Path(__file__).resolve().parent.parent / "config"
_OUT_PATH = Path(__file__).resolve().parent / "_config_constants.py"
_GEN_PATH = Path(__file__).resolve()

FLAT_YAML_FILES = ["game", 
                   "combat", 
                   "economy", 
                   "minions", 
                   "neutrals", 
                   "structures"]

_HEADER = (
    "# AUTO-GENERATED by shared/_config_gen.py from config/*.yaml — do not edit by hand.\n"
    "# Regenerated automatically on import when a source YAML file changes.\n"
)


def _load(name: str) -> dict:
    """Load a config YAML file from ``config/``."""
    with open(_CONFIG_DIR / f"{name}.yaml", "r", encoding="utf-8") as fh:
        return yaml.safe_load(fh) or {}


def generate() -> None:
    """Generate ``shared/_config_constants.py`` from the flat YAML files."""
    lines = [_HEADER]
    for name in FLAT_YAML_FILES:
        data = _load(name)
        colors = data.pop("colors", {}) if name == "game" else {}

        lines.append(f"\n# --- config/{name}.yaml ---\n")
        for key, value in data.items():
            lines.append(f"# config/{name}.yaml: {key}\n")
            lines.append(f"{key.upper()} = {value!r}\n")

        for color_name, rgb in colors.items():
            lines.append(f"# config/{name}.yaml: colors.{color_name}\n")
            lines.append(f"COLOR_{color_name.upper()} = {tuple(rgb)!r}\n")

    _OUT_PATH.write_text("".join(lines), encoding="utf-8")


def _is_stale() -> bool:
    """Return True if the generated file is missing or older than any source."""
    if not _OUT_PATH.exists():
        return True
    out_mtime = _OUT_PATH.stat().st_mtime
    sources = [_GEN_PATH] + [_CONFIG_DIR / f"{name}.yaml" for name in FLAT_YAML_FILES]
    return any(src.stat().st_mtime > out_mtime for src in sources)


def ensure_fresh() -> None:
    """Generate the constants file if it is missing or stale.

    Skipped in a frozen (PyInstaller) build. There the module's ``__file__``
    points inside the bundle's extraction directory, where ``shared/`` need not
    exist as a real directory — so `generate()` could raise at import time and
    take the whole app down on launch. A packaged build has no editable YAML to
    track anyway: it ships the already-generated `_config_constants.py`.
    """
    if getattr(sys, "frozen", False):
        return
    if _is_stale():
        generate()
