# AUTO-GENERATED by shared/_config_gen.py from config/*.yaml — do not edit by hand.
# Regenerated automatically on import when a source YAML file changes.

# --- config/game.yaml ---
# config/game.yaml: server_tick_rate
SERVER_TICK_RATE = 20
# config/game.yaml: default_host
DEFAULT_HOST = '127.0.0.1'
# config/game.yaml: default_port
DEFAULT_PORT = 7777
# config/game.yaml: max_players
MAX_PLAYERS = 10
# config/game.yaml: client_fps
CLIENT_FPS = 30
# config/game.yaml: screen_width
SCREEN_WIDTH = 1280
# config/game.yaml: screen_height
SCREEN_HEIGHT = 720
# config/game.yaml: edge_pan_margin
EDGE_PAN_MARGIN = 20
# config/game.yaml: camera_pan_speed
CAMERA_PAN_SPEED = 1000
# config/game.yaml: map_width
MAP_WIDTH = 6000
# config/game.yaml: map_height
MAP_HEIGHT = 6000
# config/game.yaml: default_kill_target
DEFAULT_KILL_TARGET = 100
# config/game.yaml: pregame_countdown
PREGAME_COUNTDOWN = 5.0
# config/game.yaml: vision_radius
VISION_RADIUS = 700
# config/game.yaml: minion_vision_radius
MINION_VISION_RADIUS = 400
# config/game.yaml: tower_vision_radius
TOWER_VISION_RADIUS = 600
# config/game.yaml: grid_cell
GRID_CELL = 512
# config/game.yaml: grid_margin
GRID_MARGIN = 200.0
# config/game.yaml: colors.bg
COLOR_BG = (40, 60, 30)
# config/game.yaml: colors.team1
COLOR_TEAM1 = (70, 130, 255)
# config/game.yaml: colors.team2
COLOR_TEAM2 = (255, 70, 70)
# config/game.yaml: colors.health_bg
COLOR_HEALTH_BG = (60, 60, 60)
# config/game.yaml: colors.health
COLOR_HEALTH = (50, 200, 50)
# config/game.yaml: colors.mana
COLOR_MANA = (70, 120, 240)
# config/game.yaml: colors.grid
COLOR_GRID = (50, 70, 40)
# config/game.yaml: colors.text
COLOR_TEXT = (240, 240, 240)
# config/game.yaml: colors.projectile
COLOR_PROJECTILE = (255, 230, 120)
# config/game.yaml: colors.structure_dead
COLOR_STRUCTURE_DEAD = (70, 70, 70)
# config/game.yaml: colors.lane
COLOR_LANE = (60, 80, 50)

# --- config/combat.yaml ---
# config/combat.yaml: hero_radius
HERO_RADIUS = 20
# config/combat.yaml: hero_move_speed
HERO_MOVE_SPEED = 140
# config/combat.yaml: hero_base_hp
HERO_BASE_HP = 600
# config/combat.yaml: hero_base_mana
HERO_BASE_MANA = 200
# config/combat.yaml: hero_attack_damage
HERO_ATTACK_DAMAGE = 55
# config/combat.yaml: hero_attack_range
HERO_ATTACK_RANGE = 100
# config/combat.yaml: hero_attack_interval
HERO_ATTACK_INTERVAL = 1.0
# config/combat.yaml: basic_projectile_speed
BASIC_PROJECTILE_SPEED = 1100
# config/combat.yaml: basic_projectile_radius
BASIC_PROJECTILE_RADIUS = 8
# config/combat.yaml: attack_click_pixels
ATTACK_CLICK_PIXELS = 14
# config/combat.yaml: hero_respawn_base
HERO_RESPAWN_BASE = 2.0
# config/combat.yaml: hero_respawn_per_level
HERO_RESPAWN_PER_LEVEL = 3.0
# config/combat.yaml: tree_respawn
TREE_RESPAWN = 20.0
# config/combat.yaml: max_level
MAX_LEVEL = 15
# config/combat.yaml: xp_base
XP_BASE = 100
# config/combat.yaml: xp_per_level
XP_PER_LEVEL = 120
# config/combat.yaml: hp_per_level
HP_PER_LEVEL = 80
# config/combat.yaml: damage_per_level
DAMAGE_PER_LEVEL = 6
# config/combat.yaml: item_slots
ITEM_SLOTS = 6
# config/combat.yaml: starting_gold
STARTING_GOLD = 600
# config/combat.yaml: tp_cost
TP_COST = 135
# config/combat.yaml: tp_range
TP_RANGE = 300
# config/combat.yaml: tp_cooldown
TP_COOLDOWN = 30.0
# config/combat.yaml: defense_k
DEFENSE_K = 100

# --- config/economy.yaml ---
# config/economy.yaml: hero_kill_gold
HERO_KILL_GOLD = 200
# config/economy.yaml: hero_kill_xp
HERO_KILL_XP = 150
# config/economy.yaml: passive_gold_per_sec
PASSIVE_GOLD_PER_SEC = 2.0
# config/economy.yaml: mana_regen_per_sec
MANA_REGEN_PER_SEC = 5.0
# config/economy.yaml: hero_hp_regen_per_sec
HERO_HP_REGEN_PER_SEC = 3.0
# config/economy.yaml: structure_gold
STRUCTURE_GOLD = 150
# config/economy.yaml: minion_assist_gold_fraction
MINION_ASSIST_GOLD_FRACTION = 0.4
# config/economy.yaml: gold_share_radius
GOLD_SHARE_RADIUS = 400
# config/economy.yaml: xp_share_radius
XP_SHARE_RADIUS = 400

# --- config/minions.yaml ---
# config/minions.yaml: minion_hp
MINION_HP = 150
# config/minions.yaml: minion_damage
MINION_DAMAGE = 18
# config/minions.yaml: minion_range
MINION_RANGE = 100
# config/minions.yaml: minion_interval
MINION_INTERVAL = 1.0
# config/minions.yaml: minion_speed
MINION_SPEED = 130
# config/minions.yaml: minion_radius
MINION_RADIUS = 15
# config/minions.yaml: minion_gold
MINION_GOLD = 25
# config/minions.yaml: minion_xp
MINION_XP = 30
# config/minions.yaml: ranged_minion_hp
RANGED_MINION_HP = 90
# config/minions.yaml: ranged_minion_damage
RANGED_MINION_DAMAGE = 22
# config/minions.yaml: ranged_minion_range
RANGED_MINION_RANGE = 230
# config/minions.yaml: ranged_minion_gold
RANGED_MINION_GOLD = 40
# config/minions.yaml: ranged_minion_xp
RANGED_MINION_XP = 60
# config/minions.yaml: ranged_minion_projectile_speed
RANGED_MINION_PROJECTILE_SPEED = 600
# config/minions.yaml: cart_minion_hp
CART_MINION_HP = 500
# config/minions.yaml: cart_minion_damage
CART_MINION_DAMAGE = 40
# config/minions.yaml: cart_minion_range
CART_MINION_RANGE = 170
# config/minions.yaml: cart_minion_speed
CART_MINION_SPEED = 120
# config/minions.yaml: cart_minion_radius
CART_MINION_RADIUS = 18
# config/minions.yaml: cart_minion_gold
CART_MINION_GOLD = 60
# config/minions.yaml: cart_minion_xp
CART_MINION_XP = 80
# config/minions.yaml: creep_wave_interval
CREEP_WAVE_INTERVAL = 30.0
# config/minions.yaml: creep_melee_per_wave
CREEP_MELEE_PER_WAVE = 3
# config/minions.yaml: creep_ranged_per_wave
CREEP_RANGED_PER_WAVE = 1
# config/minions.yaml: creep_cart_every
CREEP_CART_EVERY = 3
# config/minions.yaml: first_wave_speed_multiplier
FIRST_WAVE_SPEED_MULTIPLIER = 1.8

# --- config/neutrals.yaml ---
# config/neutrals.yaml: neutral_hp
NEUTRAL_HP = 200
# config/neutrals.yaml: neutral_damage
NEUTRAL_DAMAGE = 25
# config/neutrals.yaml: neutral_range
NEUTRAL_RANGE = 160
# config/neutrals.yaml: neutral_interval
NEUTRAL_INTERVAL = 1.0
# config/neutrals.yaml: neutral_radius
NEUTRAL_RADIUS = 14
# config/neutrals.yaml: neutral_gold
NEUTRAL_GOLD = 40
# config/neutrals.yaml: neutral_xp
NEUTRAL_XP = 45
# config/neutrals.yaml: neutral_respawn
NEUTRAL_RESPAWN = 60.0

# --- config/structures.yaml ---
# config/structures.yaml: tower_hp
TOWER_HP = 1600
# config/structures.yaml: tower_damage
TOWER_DAMAGE = 80
# config/structures.yaml: tower_range
TOWER_RANGE = 340
# config/structures.yaml: tower_interval
TOWER_INTERVAL = 1.5
# config/structures.yaml: tower_radius
TOWER_RADIUS = 30
# config/structures.yaml: tower_projectile_speed
TOWER_PROJECTILE_SPEED = 700
# config/structures.yaml: core_hp
CORE_HP = 4000
# config/structures.yaml: core_damage
CORE_DAMAGE = 150
# config/structures.yaml: core_radius
CORE_RADIUS = 80
